spring.application.name=emergency-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/emergencydb
spring.datasource.username=postgres
spring.datasource.password=Nithya@888

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true