spring.datasource.url=jdbc:postgresql://dpg-d6lsrsq4d50c73ch0s60-a.oregon-postgres.render.com:5432/healthapp_99zu
spring.datasource.username=healthuser
spring.datasource.password=xKgsXVLi4XArPcultI7P5beL5k70NACx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true